steps:
  - task: Docker@2
    displayName: Login to ACR dev
    inputs:
      command: login
      containerRegistry: stratsysContainerRegistry
  - task: Docker@2
    displayName: Login to ACR prod
    inputs:
      command: login
      containerRegistry: stratsysProductionContainerRegistry
  - script: |
      . build.sh
    displayName: 'Build'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  - task: Docker@2
    displayName: Logout from ACR dev
    inputs:
      command: logout
      containerRegistry: stratsysContainerRegistry
  - task: Docker@2
    displayName: Logout from ACR prod
    inputs:
      command: logout
      containerRegistry: stratsysProductionContainerRegistry
  - script: |
      . remove_dockerimage.sh
    displayName: 'Remove built image'
trigger:
  - master
pool: "Linux-docker"